blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/soulcorrea/lucide-svg-rs/security/policy
    about: Please report security vulnerabilities privately.
