name: Commit Message Lint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint PR title with commitlint
        uses: JulienKode/pull-request-name-linter-action@v0.5.0
        with:
          configuration-path: commitlint.config.json
