name: Patch Badges

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Patch README badges with OWNER/REPO (and optional Codecov token)
        shell: bash
        env:
          REPO_FULL: ${{ github.repository }}
          CODECOV_BADGE_TOKEN: ${{ secrets.CODECOV_BADGE_TOKEN }}
        run: |
          set -euo pipefail
          OWNER="${REPO_FULL%/*}"
          REPO="${REPO_FULL#*/}"
          FILE="README.md"

          if [[ ! -f "$FILE" ]]; then
            echo "README.md not found; skipping."
            exit 0
          fi

          echo "Patching badges for $OWNER/$REPO"

          sed -i "s#https://github.com/soulcorrea/lucide-svg-rs/actions/workflows/ci.yml#https://github.com/${OWNER}/${REPO}/actions/workflows/ci.yml#g" "$FILE"
          sed -i "s#https://github.com/soulcorrea/lucide-svg-rs/actions/workflows/release.yml#https://github.com/${OWNER}/${REPO}/actions/workflows/release.yml#g" "$FILE"

          sed -i "s#https://codecov.io/gh/OWNER/REPO/branch/main/graph/badge.svg?token=YOURTOKEN#https://codecov.io/gh/${OWNER}/${REPO}/branch/main/graph/badge.svg#g" "$FILE"
          sed -i "s#https://codecov.io/gh/OWNER/REPO#https://codecov.io/gh/${OWNER}/${REPO}#g" "$FILE"

          if [[ -n "${CODECOV_BADGE_TOKEN:-}" ]]; then
            sed -i "s#codecov\.io/gh/${OWNER}/${REPO}/branch/main/graph/badge\.svg#codecov.io/gh/${OWNER}/${REPO}/branch/main/graph/badge.svg?token=${CODECOV_BADGE_TOKEN}#g" "$FILE"
          else
            sed -i "s#\?token=YOURTOKEN##g" "$FILE"
          fi

          if git diff --quiet -- "$FILE"; then
            echo "No badge changes detected."
          else:
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add "$FILE"
            git commit -m "chore(badges): patch README badges to ${OWNER}/${REPO}"
            git push
            echo "Badges patched and pushed."
          fi

      - name: Show README header (debug)
        shell: bash
        run: |
          head -n 40 README.md || true
