name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  plan:
    name: Plan release (cargo-dist)
    runs-on: ubuntu-latest
    outputs:
      plan: ${{ steps.plan.outputs.plan }}
      tag: ${{ steps.plan.outputs.tag }}
      version: ${{ steps.plan.outputs.version }}
      publish: ${{ steps.plan.outputs.publish }}
      artifacts_matrix: ${{ steps.plan.outputs.artifacts_matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist@0.20.0
      - id: plan
        run: |
          cargo dist plan --tag "$GITHUB_REF_NAME" --output-format json > plan.json
          echo "plan=$(cat plan.json)" >> "$GITHUB_OUTPUT"
          echo "tag=$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
          echo "publish=true" >> "$GITHUB_OUTPUT"
          ARTIFACTS=$(jq -r '.artifacts | to_entries | map({artifact: .key, platform: .value.platform})' plan.json)
          echo "artifacts_matrix=${ARTIFACTS}" >> "$GITHUB_OUTPUT"
      - name: Upload dist plan
        uses: actions/upload-artifact@v4
        with:
          name: cargo-dist-plan
          path: plan.json

  build:
    name: Build artifacts (cargo-dist)
    needs: plan
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.plan.outputs.artifacts_matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.rust-target }}
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist@0.20.0
      - name: Build with cargo-dist
        run: cargo dist build --artifacts ${{ matrix.artifact }} --tag "${{ needs.plan.outputs.tag }}"
      - name: Upload cargo-dist outputs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            target/distrib/**/*
            !target/distrib/**/*.json

  finalize:
    name: Sign, SBOM, packaging, and publish release
    needs: [plan, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Collate release files
        run: |
          mkdir -p dist
          find artifacts -type f -name '*' -exec cp {} dist/ \;
          echo "Files to release:"
          ls -l dist || true

      - name: Generate SBOM (CycloneDX)
        run: |
          cargo install --locked cargo-cyclonedx
          cargo cyclonedx --all --format json --output-file dist/SBOM.cdx.json

      - name: Generate checksums
        shell: bash
        run: |
          cd dist
          find . -type f ! -name "*.sha256" ! -name "*.json" -print0 | xargs -0 -I{} sh -c 'sha256sum "{}" >> CHECKSUMS.sha256'
          cat CHECKSUMS.sha256

      - name: Import GPG key (optional)
        if: ${{ secrets.GPG_PRIVATE_KEY != '' }}
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Sign checksums with GPG (optional)
        if: ${{ secrets.GPG_PRIVATE_KEY != '' }}
        run: |
          cd dist
          gpg --batch --yes --armor --detach-sign --output CHECKSUMS.sha256.asc CHECKSUMS.sha256
          ls -l CHECKSUMS.sha256.asc

      - name: Generate Homebrew & Scoop files
        shell: bash
        run: |
          set -euo pipefail
          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          VERSION="${{ needs.plan.outputs.version }}"
          TAG="${{ needs.plan.outputs.tag }}"

          LINUX_ZIP=$(ls dist/*linux*.* 2>/dev/null | head -n1 || true)
          MAC_X86_ZIP=$(ls dist/*darwin*x86_64*.* 2>/dev/null | head -n1 || true)
          MAC_ARM_ZIP=$(ls dist/*darwin*aarch64*.* 2>/dev/null | head -n1 || true)
          WIN_ZIP=$(ls dist/*windows*x86_64*.* 2>/dev/null | head -n1 || true)

          sha_or_empty () { test -f "$1" && sha256sum "$1" | cut -d' ' -f1 || echo ""; }

          LINUX_SHA=$(sha_or_empty "${LINUX_ZIP:-}")
          MAC_X86_SHA=$(sha_or_empty "${MAC_X86_ZIP:-}")
          MAC_ARM_SHA=$(sha_or_empty "${MAC_ARM_ZIP:-}")
          WIN_SHA=$(sha_or_empty "${WIN_ZIP:-}")

          mkdir -p outpkg/homebrew outpkg/scoop

          cat > outpkg/homebrew/lucide-offline-cli.rb <<'RUBY'
class LucideOfflineCli < Formula
  desc "Offline Lucide icons CLI and library"
  homepage "https://github.com/soulcorrea/lucide-svg-rs"
  version "VERSION"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/soulcorrea/lucide-svg-rs/releases/download/vVERSION/lucide-offline-cli-macos-aarch64.zip"
      sha256 "SHA256_MAC_ARM64"
    else
      url "https://github.com/soulcorrea/lucide-svg-rs/releases/download/vVERSION/lucide-offline-cli-macos-x86_64.zip"
      sha256 "SHA256_MAC_X86_64"
    end
  end

  on_linux do
    url "https://github.com/soulcorrea/lucide-svg-rs/releases/download/vVERSION/lucide-offline-cli-linux-x86_64.zip"
    sha256 "SHA256_LINUX_X86_64"
  end

  def install
    bin.install "lucide-offline-cli"
  end

  test do
    system "#{bin}/lucide-offline-cli", "list"
  end
end
RUBY

          sed -i "s/OWNER/${OWNER}/g" outpkg/homebrew/lucide-offline-cli.rb
          sed -i "s/REPO/${REPO}/g" outpkg/homebrew/lucide-offline-cli.rb
          sed -i "s/VERSION/${VERSION}/g" outpkg/homebrew/lucide-offline-cli.rb
          sed -i "s/SHA256_MAC_ARM64/${MAC_ARM_SHA}/g" outpkg/homebrew/lucide-offline-cli.rb
          sed -i "s/SHA256_MAC_X86_64/${MAC_X86_SHA}/g" outpkg/homebrew/lucide-offline-cli.rb
          sed -i "s/SHA256_LINUX_X86_64/${LINUX_SHA}/g" outpkg/homebrew/lucide-offline-cli.rb

          cat > outpkg/scoop/lucide-offline-cli.json <<'JSON'
{
  "version": "VERSION",
  "description": "Offline Lucide icons CLI and library",
  "homepage": "https://github.com/soulcorrea/lucide-svg-rs",
  "license": "MIT OR Apache-2.0",
  "architecture": {
    "64bit": {
      "url": "https://github.com/soulcorrea/lucide-svg-rs/releases/download/vVERSION/lucide-offline-cli-windows-x86_64.zip",
      "hash": "SHA256_WINDOWS_X86_64",
      "bin": [ "lucide-offline-cli.exe" ]
    }
  }
}
JSON

          sed -i "s/OWNER/${OWNER}/g" outpkg/scoop/lucide-offline-cli.json
          sed -i "s/REPO/${REPO}/g" outpkg/scoop/lucide-offline-cli.json
          sed -i "s/VERSION/${VERSION}/g" outpkg/scoop/lucide-offline-cli.json
          sed -i "s/SHA256_WINDOWS_X86_64/${WIN_SHA}/g" outpkg/scoop/lucide-offline-cli.json

          echo "Generated packaging files:"
          ls -l outpkg/homebrew outpkg/scoop || true

      - name: Auto-push Homebrew formula (optional)
        if: ${{ secrets.GH_PAT != '' && secrets.HOMEBREW_TAP_REPO != '' }}
        shell: bash
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone "https://${{ secrets.GH_PAT }}@github.com/${{ secrets.HOMEBREW_TAP_REPO }}.git" taprepo
          mkdir -p taprepo/Formula
          cp outpkg/homebrew/lucide-offline-cli.rb taprepo/Formula/lucide-offline-cli.rb
          cd taprepo
          git add Formula/lucide-offline-cli.rb
          git commit -m "Update lucide-offline-cli formula to ${{ needs.plan.outputs.tag }}"
          git push

      - name: Auto-push Scoop manifest (optional)
        if: ${{ secrets.GH_PAT != '' && secrets.SCOOP_BUCKET_REPO != '' }}
        shell: bash
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone "https://${{ secrets.GH_PAT }}@github.com/${{ secrets.SCOOP_BUCKET_REPO }}.git" scooprepo
          mkdir -p scooprepo/bucket
          cp outpkg/scoop/lucide-offline-cli.json scooprepo/bucket/lucide-offline-cli.json
          cd scooprepo
          git add bucket/lucide-offline-cli.json
          git commit -m "Update lucide-offline-cli manifest to ${{ needs.plan.outputs.tag }}"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.plan.outputs.tag }}
          files: |
            dist/*
            outpkg/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
